package com.swapnil.etfscanner

/**
 * The ETF universe carried over from the "Mack ETF Strategy" sheet.
 * Symbol is the NSE ticker (Yahoo uses "<symbol>.NS"); category is kept
 * from the sheet because Yahoo doesn't provide it for Indian ETFs.
 */
data class EtfRef(val symbol: String, val category: String)

object EtfUniverse {
    val list: List<EtfRef> = listOf(
        EtfRef("SENSEXIETF", "Other"),
        EtfRef("INFRAIETF", "Other"),
        EtfRef("TNIDETF", "Other"),
        EtfRef("MOLOWVOL", "Other"),
        EtfRef("HDFCSILVER", "Other"),
        EtfRef("ABSLBANETF", "Other"),
        EtfRef("SILVERBEES", "Other"),
        EtfRef("SILVERIETF", "Other"),
        EtfRef("SBIETFQLTY", "Other"),
        EtfRef("CONSUMIETF", "Other"),
        EtfRef("BANKIETF", "Banking"),
        EtfRef("HEALTHIETF", "Other"),
        EtfRef("NIFTYQLITY", "IT"),
        EtfRef("MOHEALTH", "Other"),
        EtfRef("AXISHCETF", "Other"),
        EtfRef("HDFCLOWVOL", "Other"),
        EtfRef("CONSUMBEES", "Other"),
        EtfRef("GOLDBEES", "Other"),
        EtfRef("AXISILVER", "Other"),
        EtfRef("AUTOIETF", "Other"),
        EtfRef("HDFCMOMENT", "Other"),
        EtfRef("SETFGOLD", "Broad Market"),
        EtfRef("ALPHAETF", "Other"),
        EtfRef("QGOLDHALF", "Other"),
        EtfRef("HDFCNIF100", "Other"),
        EtfRef("SILVER", "Other"),
        EtfRef("UTINIFTETF", "Other"),
        EtfRef("NIF100BEES", "Other"),
        EtfRef("HDFCNEXT50", "Other"),
        EtfRef("INFRABEES", "Other"),
        EtfRef("NEXT50IETF", "Other"),
        EtfRef("MOM30IETF", "Other"),
        EtfRef("GOLDIETF", "Other"),
        EtfRef("JUNIORBEES", "Other"),
        EtfRef("HDFCGOLD", "Other"),
        EtfRef("DIVOPPBEES", "Other"),
        EtfRef("GOLDSHARE", "Other"),
        EtfRef("NV20BEES", "Other"),
        EtfRef("BSLNIFTY", "Broad Market"),
        EtfRef("HDFCBSE500", "Other"),
        EtfRef("QUAL30IETF", "Other"),
        EtfRef("GOLDETF", "Other"),
        EtfRef("ABSLNN50ET", "Other"),
        EtfRef("ESILVER", "Other"),
        EtfRef("NIFTYETF", "Broad Market"),
        EtfRef("BSE500IETF", "Other"),
        EtfRef("FINIETF", "Other"),
        EtfRef("SENSEXETF", "Other"),
        EtfRef("AXISGOLD", "Other"),
        EtfRef("ICICIB22", "Other"),
        EtfRef("FMCGIETF", "Other"),
        EtfRef("NIFTYBEES", "Broad Market"),
        EtfRef("MOM100", "Other"),
        EtfRef("SETFNN50", "Broad Market"),
        EtfRef("PSUBNKBEES", "Banking"),
        EtfRef("SBIETFIT", "IT"),
        EtfRef("LOWVOLIETF", "Other"),
        EtfRef("MIDCAPETF", "Other"),
        EtfRef("AXISBNKETF", "Other"),
        EtfRef("HEALTHY", "Other"),
        EtfRef("BANKETF", "Banking"),
        EtfRef("NIF100IETF", "Other"),
        EtfRef("CPSEETF", "Other"),
        EtfRef("ITETF", "IT"),
        EtfRef("ITIETF", "IT"),
        EtfRef("BANKBEES", "Banking"),
        EtfRef("MON100", "Other"),
        EtfRef("SETFNIFBK", "Broad Market"),
        EtfRef("MAKEINDIA", "Other"),
        EtfRef("MONQ50", "Other"),
        EtfRef("AUTOBEES", "Other"),
        EtfRef("MIDSELIETF", "Other"),
        EtfRef("HDFCNIFTY", "Broad Market"),
        EtfRef("UTIBANKETF", "Banking"),
        EtfRef("PSUBNKIETF", "Banking"),
        EtfRef("PVTBANIETF", "Other"),
        EtfRef("UTINEXT50", "Other"),
        EtfRef("HDFCSML250", "Other"),
        EtfRef("TECH", "Other"),
        EtfRef("NV20IETF", "Other"),
        EtfRef("MAHKTECH", "Other"),
        EtfRef("BFSI", "Other"),
        EtfRef("ALPL30IETF", "Other"),
        EtfRef("NIFTYIETF", "Broad Market"),
        EtfRef("MONIFTY500", "Broad Market"),
        EtfRef("SETFNIF50", "Broad Market"),
        EtfRef("COMMOIETF", "Other"),
        EtfRef("MIDCAPIETF", "Other"),
        EtfRef("BSLGOLDETF", "Other"),
        EtfRef("MOVALUE", "Other"),
        EtfRef("MID150BEES", "Other"),
        EtfRef("MOMOMENTUM", "Other"),
        EtfRef("SILVERETF", "Other"),
        EtfRef("ITBEES", "IT"),
        EtfRef("MOMENTUM", "Other"),
        EtfRef("HNGSNGBEES", "Other"),
        EtfRef("MASPTOP50", "Other"),
        EtfRef("HDFCMID150", "Other"),
        EtfRef("PHARMABEES", "Pharma")
    )
}
